### ISSUE TITLE
TLS handshake error 

### ISSUE THREAD

**Issue by jacyzin** [indeedeng/harbor-container-webhook#41]
I've been trying install the harbor-container webhook in GKE autopilot or standard.
webhook-config.yaml:
```
 port: 9443
    certDir: "/etc/hcw/certs"
    metricsAddr: ":8080"
    healthAddr: ":8090"
    verbose: false
    rules:
       - name: 'docker.io rewrite rule'
         matches:
           - '^docker.io'
         excludes: []
         replace: 'harbor.gambi-cat.store'
         checkUpstream: false
```
redis-example.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: docker.io/redis:7.0.15
      ports:
        - containerPort: 6379
```
When I run:
`kubectl apply -f redis-example.yaml`

Occurr the same error in pod harbor-container-webhook:
`2024/09/19 17:14:46 http: TLS handshake error from 10.x.x.x:35816: EOF`

There are any limitation running harbor-container-webhook in GKE?
