### ISSUE TITLE
not muttating pods

### ISSUE THREAD

**Issue by ichasco-heytrade** [indeedeng/harbor-container-webhook#46]
Hi, I have deployed the webhook but it doesn't mutate any pod

This is the config:

```
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
    tag: "main"
  imagePullSecrets: []
  nameOverride: harbor-container-webhook
  fullnameOverride: harbor-container-webhook
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  podAnnotations:
    fluentbit.io/exclude: "true"
  podSecurityContext: {}
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
  service:
    type: ClusterIP
    port: 9443
  additionalVolumeMounts: []
  additionalVolumes: []
  initContainers: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraArgs: []
  extraEnv: []
  priorityClassName: ""
  certManager:
    enabled: true
    apiVersion: "cert-manager.io/v1"
    duration: 2160h0m0s
    renewBefore: 360h0m0s
  webhook:
    namespaceSelector:
      matchExpressions:
        - key: "goharbor.io/harbor-container-webhook-disable"
          operator: NotIn
          values: ["true"]
    objectSelector:
      matchExpressions:
        - key: "goharbor.io/harbor-container-webhook-disable"
          operator: NotIn
          values: ["true"]
    failurePolicy: Ignore
  rules:
    - name: 'docker.io rewrite rule'
      matches:
        - '^docker.io'
      excludes:
        - '.*goharbor.*'
        - '.*auto.*'
      replace: 'harbor.xxxxxx.com/docker-hub-cache'
      checkUpstream: true
  extraRules: []
  certDir: ""
  prometheus:
    enabled: true
    port: 8080
  healthPort: 8090
  verbose: true
  metrics:
    serviceMonitor:
      enabled: false
      jobLabel: ""
      interval: ""
      scrapeTimeout: ""
      honorLabels: false
      metricRelabelings: []
      relabelings: []
      labels: {}
      scheme: http
```

There isn't any error log :(
