### ISSUE TITLE
The webhook tries to rewrite when it shouldn't

### ISSUE THREAD

**Issue by adrian-salas** [indeedeng/harbor-container-webhook#55]
Hi !

We have been using this repo at work as proxy to docker images.
However, i think we found a specific case where the webhook rewrites to harbor when it shouldn't.

Here is the current config for the webhook:

```
port: 9443
certDir: "/etc/hcw/certs"
metricsAddr: "0"
healthAddr: ":8090"
verbose: false
rules:
  - checkUpstream: false
    matches:
    - ^docker.io
    name: docker.io rewrite rule
    replace: HARBOR-URL/docker_proxy
```

and here is a CI job that asks for an image:

```
  image: ghcr.io/nosinovacao/dotnet-sonar:23.02.4
```

In theory, the webhook shouldn't try to rewrite since the regex doesn't match but i can see that it does:

![Image](https://github.com/user-attachments/assets/eecd2218-a0bc-4ede-b87c-8605f292d0ad)

I tried adding exclude rules without success, it still tries to rewrite that.

PS: The repository in question is a bit specific since the tag 23.02.4 does exists in the ghcr registry, but not in the dockerhub registry. So in the end, the job fails because harbor tries to pull from dockerhub (where the image isn't present)
